import type { CharacterView } from "./types";
export const demo: CharacterView = {
  id: "preview",
  userId: "preview",
  schemaVersion: 2,
  revision: 0,
  level: 3,
  createdAt: "2026-09-09",
  updatedAt: "2026-09-09",
  choices: {
    name: "Vaelis Moonweaver",
    classId: "wizard",
    speciesId: "elf",
    backgroundId: "sage",
    startingEquipment: "package",
    method: "standard",
    baseScores: {
      strength: 8,
      dexterity: 14,
      constitution: 13,
      intelligence: 15,
      wisdom: 12,
      charisma: 10,
    },
    boosts: {
      strength: 0,
      dexterity: 0,
      constitution: 1,
      intelligence: 2,
      wisdom: 0,
      charisma: 0,
    },
    skills: ["Insight", "Investigation"],
    spells: [
      "fire-bolt",
      "mage-hand",
      "light",
      "magic-missile",
      "shield",
      "misty-step",
    ],
    narrative:
      "The stars have always whispered to Vaelis. Once a keeper of the silver archives, he now follows a constellation that appears on no chart—carrying a weathered spellbook, a quiet curiosity, and a promise he has yet to keep.",
    appearance: { palette: "jade", accessory: "staff" },
  },
  advancements: [2, 3].map((level) => ({
    level,
    boosts: {
      strength: 0,
      dexterity: 0,
      constitution: 0,
      intelligence: 0,
      wisdom: 0,
      charisma: 0,
    },
    feat: "",
    hp: 4,
  })),
  state: {
    hp: 20,
    tempHp: 0,
    hitDiceUsed: 0,
    slotsUsed: [1, 0, 0, 0, 0, 0, 0, 0, 0],
    resourcesUsed: {},
    conditions: [],
    exhaustion: 0,
    deathSaves: { success: 0, failure: 0 },
    concentration: null,
    inventory: [
      { id: "quarterstaff", quantity: 1, equipped: true },
      { id: "spellbook", quantity: 1, equipped: false },
      { id: "arcane-focus", quantity: 1, equipped: false },
    ],
    gold: 15,
    notes: "A new chapter begins at the edge of the known world.",
  },
  history: [],
  derived: {
    scores: {
      strength: 8,
      dexterity: 14,
      constitution: 14,
      intelligence: 17,
      wisdom: 12,
      charisma: 10,
    },
    modifiers: {
      strength: -1,
      dexterity: 2,
      constitution: 2,
      intelligence: 3,
      wisdom: 1,
      charisma: 0,
    },
    proficiency: 2,
    maxHp: 20,
    armorClass: 12,
    speed: 30,
    initiative: 2,
    saves: {
      strength: -1,
      dexterity: 2,
      constitution: 2,
      intelligence: 5,
      wisdom: 3,
      charisma: 0,
    },
    skills: {
      Acrobatics: 2,
      "Animal Handling": 1,
      Arcana: 5,
      Athletics: -1,
      Deception: 0,
      History: 5,
      Insight: 3,
      Intimidation: 0,
      Investigation: 5,
      Medicine: 1,
      Nature: 3,
      Perception: 1,
      Performance: 0,
      Persuasion: 0,
      Religion: 3,
      "Sleight of Hand": 2,
      Stealth: 2,
      Survival: 1,
    },
    spellLimits: { cantrips: 3, prepared: 6 },
    spellAbility: "intelligence",
    spellAttack: 5,
    spellDc: 13,
    slots: [4, 2, 0, 0, 0, 0, 0, 0, 0],
    resources: [
      { id: "arcane-recovery", name: "Arcane Recovery", max: 1, rest: "long" },
    ],
    features: [
      {
        name: "Magic Initiate (Wizard)",
        level: 1,
        page: 87,
        text: "Your Sage background grants the Magic Initiate Origin feat.",
      },
      {
        name: "Spellcasting",
        level: 1,
        page: 77,
        text: "Study your spellbook and prepare magic for the journey ahead. Your spellcasting ability is Intelligence.",
      },
      {
        name: "Arcane Recovery",
        level: 1,
        page: 78,
        text: "Recover expended spell slots after a Short Rest, once per Long Rest. See the SRD for the recovery budget.",
      },
      {
        name: "Evoker",
        level: 3,
        page: 81,
        text: "An evoker studies magic that creates powerful elemental effects. Read the SRD subclass features before applying their effects.",
      },
    ],
    attacks: [{ name: "Quarterstaff", bonus: 1, damage: "1d6 − 1" }],
  },
};
